---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: em9va2VlcGVyc3RvcmFnZQ==
  azurestorageaccountkey: SW12eTdVaUNseHNLSUV1SGo3a2Y3RE4vTFJIc3lFd3hmMlhuZVk0WnRKTnRLVlNjRkorYi9rS2hsc3BOTm1hZnZwbGJGSk0wM0d3a2VpVlpPd1JZeGc9PQ==
