# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

#Services
image: hackd.azurecr.io/elasticsearch-kubernetes:0.2
image_pull_secret: regsecret
name: elasticsearch
port: 9200
port_name: http
port_selector: elasticsearch-data
cluster_name: elasticsearch-cluster
cluster_port: 9300
cluster_port_name: cluster-comms

#Master StatefulSet
master_name: elasticsearch-master
# master_replicas: if changing this value, please also update the
# elasticsearch configuration file quorum settings in the
# samsung_cnct/elasticsearch image. This value should not be altered
# when running in production
master_replicas: 3
master_imagePullPolicy: Always
master_cpu_limits: 500m
master_cpu_requests: 500m
master_memory_limits: 6Gi
master_memory_requests: 6Gi
# master_volume_storage: set to small so when exploring with this the
# user doesn't accidentally create very large disks
master_volume_storage: 128Gi
# Xms & Xmx: must be the same
# should be ~75% of total memory allocation
master_Xms_Xmx: 4g

#Cluster StatefulSet
data_name: elasticsearch-data
# data_replicas: This can be changed at will for scaling purposes
# either in this chart or at the command line during production
data_replicas: 3
# resource notes:  datanodes are pretty heavy.
# These should be modified up for a real production setting
# recommendation is two cores and 20GB of memory for the containers
data_cpu_limits: 500m
data_memory_limits: 6Gi
data_cpu_requests: 500m
data_memory_requests: 6Gi
data_volume_storage: 200Gi
# Xms & Xmx: must be the same
# should be ~75% of total memory allocation
data_Xms_Xmx: 4g
