# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Name: es
PeerPort: 2380
ClientPort: 2379
Component: "elasticsearch"
#Image: "jetstack/elasticsearch-pet"
Image: "jetstack/elasticsearch-pet"
ImageTag: "2.4.0"
#ImageTag: "5.2.2"
ImagePullPolicy: "Always"
ClientReplicas: 2
ClientCpuRequests: "25m"
ClientMemoryRequests: "256Mi"
ClientCpuLimits: "1"
ClientMemoryLimits: "512Mi"
ClientHeapSize: "128m"
MasterReplicas: 2
MasterCpuRequests: "25m"
MasterMemoryRequests: "256Mi"
MasterCpuLimits: "1"
MasterMemoryLimits: "512Mi"
MasterHeapSize: "128m"
DataReplicas: 2
DataCpuRequests: "250m"
DataMemoryRequests: "750m"
DataCpuLimits: "1"
DataMemoryLimits: "1Gi"
DataHeapSize: "1536m"
DataStorage: "128Gi"
# DataStorageClass: "ssd"
DataStorageClass: "fast"
DataTerminationGracePeriodSeconds: 3600
ServiceDns: "elasticsearch-es"
#ServiceDns: {{ printf "%s-cluster-%s" .Release.Name .Values.Name | trunc 24 }}
